version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - DB_DRIVER=sqlite
      - SQLITE_PATH=/app/data/app.db
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - LOG_LEVEL=info
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - postgres
      - mongo
    networks:
      - fx-gin-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fx_gin_scaffold
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fx-gin-network

  mongo:
    image: mongo:7
    environment:
      - MONGO_INITDB_DATABASE=fx_gin_scaffold
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fx-gin-network

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fx-gin-network

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - fx-gin-network

volumes:
  postgres_data:
  mongo_data:
  redis_data:

networks:
  fx-gin-network:
    driver: bridge